export const routes = {
  Home: "/",
  Animation: "/animation",
  Keyframes: "/keyframes",
  Variants: "/variants",
  Gesture: "/gesture",
  Drag: "/drag",
  Motion_Values: "/motionValues",
  Scroll_Triggered: "/scroll-triggered",
  Scroll_Linked: "/scroll-linked",
  Exit: "/exit",
  Layout: "/layout",
  Shared_Layout: "/shared-layout",
  Line_Drawing: "/line-drawing",
  Path_Morphing: "/path-morphing",
  React_Router: "/react-router",
};

export const links = [
  { link: routes.Home, name: "Home" },
  { link: routes.Animation, name: "Animation" },
  { link: routes.Keyframes, name: "Keyframes" },
  { link: routes.Variants, name: "Variants" },
  { link: routes.Gesture, name: "Gesture" },
  { link: routes.Drag, name: "Drag" },
  { link: routes.Motion_Values, name: "Motion Values" },
  { link: routes.Scroll_Triggered, name: "Scroll Triggered" },
  { link: routes.Scroll_Linked, name: "Scroll Linked" },
  { link: routes.Exit, name: "Exit" },
  { link: routes.Layout, name: "Layout" },
  { link: routes.Shared_Layout, name: "Shared Layout" },
  { link: routes.Line_Drawing, name: "Line Drawing" },
  { link: routes.Path_Morphing, name: "Path Morphing" },
  { link: routes.React_Router, name: "React Router" },
];
